# Generated by Django 3.2.25 on 2025-04-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('number_box', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('at_work', models.BooleanField(default=False)),
                ('halls', models.ManyToManyField(related_name='masters', to='catalog.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id_work', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('time_on_work', models.DecimalField(decimal_places=0, max_digits=72)),
                ('ready', models.BooleanField(default=False)),
                ('allowed', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='catalog.master')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='catalog.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('at_work', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='catalog.box')),
                ('specializations', models.ManyToManyField(related_name='workers', to='catalog.Specialization')),
                ('works', models.ManyToManyField(blank=True, related_name='workers', to='catalog.Work')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='catalog.hall'),
        ),
    ]
