# Generated by Django 3.2.25 on 2025-04-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_specialization_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='allowed',
            field=models.IntegerField(default=False),
        ),
    ]
