# Generated by Django 3.2.25 on 2025-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_work_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='allowed',
        ),
        migrations.AlterField(
            model_name='work',
            name='time_on_work',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
